### ISSUE TITLE
Showing 'No Skill in Training'  when there is

### ISSUE THREAD

**Issue by ficti0n1** [cvweiss/skillq#13] opened 2018-04-05 09:54 UTC
Skillq showing 'no skill in training' when there is a large active queue:

![image](https://user-images.githubusercontent.com/36131270/38359237-abc3e1ea-38bf-11e8-8fe2-8b4805ca5438.png)

![image](https://user-images.githubusercontent.com/36131270/38359246-b287d4b4-38bf-11e8-9db3-7aa7ca38d109.png)

**Comment by cvweiss** [comment] 2018-04-05 13:52
Please verify that the character's skill queue isn't paused?

**Comment by ficti0n1** [comment] 2018-04-05 14:04
It's not and hasn't been for over 48 hours.

![image](https://user-images.githubusercontent.com/36131270/38370729-b0ff5d7e-38e2-11e8-817a-f6061c9d6e6c.png)

**Comment by ficti0n1** [comment] 2018-04-05 14:05
It's not and hasn't been in over 48 hours

![image](https://user-images.githubusercontent.com/36131270/38370767-ca8ca2ec-38e2-11e8-84e8-04b7df4b7133.png)

**Comment by cvweiss** [comment] 2018-04-05 22:26
At this time I'm unable to reproduce the bug. A skill is showing as training when I view the character.

Might be worth noting this could be an issue related to downtime, I will have to keep an eye out for issues at that time.

**Comment by mmolitor87** [comment] 2018-04-08 21:41
I have the same issue happen with multiple characters, but it seems the primary 2 are alpha characters. If I remove them and add them back it does not resolve the issue, but revoking the token and creating a new one correctly pulls the skill. I honestly cannot say if downtime is a factor.

**Comment by cvweiss** [comment] 2018-04-09 00:56
I think I need to see this when it happens so I can diagnose which query isn't returning the expected results. I'm going to reopen this issue for now to help bring more visibility to it.

**Comment by ficti0n1** [comment] 2018-04-09 13:02
My character was not alpha.

**Comment by mmolitor87** [comment] 2018-04-09 16:53
I should clarify, 2 of my character were omega, 2 were alpha.

**Comment by elite3vil** [comment] 2018-04-12 20:04
I'm also having this issue with multiple characters. I have received emails the past couple days for "less than a day in queue" when I haven't changed the queue in >7days and it looks like this.

![pricer](https://user-images.githubusercontent.com/36139263/38701159-2cc21f4a-3e6b-11e8-895a-4e4310ce6c65.PNG)

**Comment by cvweiss** [comment] 2018-04-12 20:15
@elite3vil When you pull up the character's page on skillq, does it ask you to re-log in the character because of missing scopes?

**Comment by elite3vil** [comment] 2018-04-12 20:18
Not currently, no.

**Comment by gokeefe** [comment] 2018-04-13 17:48
Not sure if the fix committed is live but this is still occurring on one of my accounts. Multiple characters on two accounts show no issues. All characters on one account are affected. I've tried reauthing the characters and that doesn't appear to have helped.

**Comment by cvweiss** [comment] 2018-04-13 18:28
Helps a lot if I re-enable the cronjob... check now please @gokeefe

**Comment by gokeefe** [comment] 2018-04-14 01:17
All good now, thanks

**Comment by cvweiss** [comment] 2018-04-25 20:54
Seems all is well now, closing issue.

**Closed by cvweiss** 2018-04-25 20:54 UTC
Labels: bug
